/*
 * This source file was generated by the Gradle 'init' task
 */
package peoplegpt;

import peoplegpt.console.GPTConsole;

public class App {

    public static void main(String[] args) {
        GPTConsole.run();
    }
}
